name: CI

on:
  release:
    types: [created]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Deploy
        run: ssh -4 root@realja.me "cd ~/textarea && git fetch origin master && git reset --hard origin/master && docker-compose up --build --remove-orphans --detach" # && git fetch && git checkout HEAD src"
